// web-quiz/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { LoginRegisterLayoutComponent } from '../../components/login-register-layout/login-register-layout.component';
import { PrimaryInputComponent } from '../../components/inputs/primary-input/primary-input.component';
import { PrimaryButtonComponent } from '../../components/buttons/primary-button/primary-button.component';
import { FormControl, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { UsuarioService } from '../../services/usuario/usuario.service';
import UsuarioDTO from '../../../models/UsuarioDTO';
import LoginRequestDTO from '../../../models/LoginRequestDTO';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  imports: [
    LoginRegisterLayoutComponent,
    PrimaryInputComponent,
    PrimaryButtonComponent,
    ReactiveFormsModule,
  ],
  templateUrl: './login.component.html',
  styleUrl: './login.component.scss',
})
export class LoginComponent {
  constructor(
    private _usuarioService: UsuarioService,
    private router: Router
  ) {}

  loginForm = new FormGroup({
    email: new FormControl(''),
    senha: new FormControl(''),
  });

  efetuarLogin(): void {
    if (this.loginForm.valid) {
      let login = new LoginRequestDTO(
        this.loginForm.value.email || '',
        this.loginForm.value.senha || ''
      );

      this._usuarioService.logar(login).subscribe({
        next: (usuario) => {
          this._usuarioService.setAuthToken(usuario.token);
          this.router.navigate(['/']);
        },
        error: (error) => {
          console.log('Erro ao efetuar login');
        },
      });
    }
  }
}

<app-login-register-layout>
  <h1>Entre em sua conta!</h1>

  <form [formGroup]="loginForm">
    <app-primary-input
      labelTitle="E-mail:"
      type="text"
      placeholder="Email"
      name="email"
      formControlName="email"
    >
    </app-primary-input>

    <app-primary-input
      labelTitle="Senha:"
      type="password"
      placeholder="Senha"
      name="senha"
      formControlName="senha"
    >
    </app-primary-input>

    <app-primary-button
      buttonLabel="Entrar"
      buttonType="submit"
      (onClick)="efetuarLogin()"
    >
    </app-primary-button>
  </form>
  <p>Não tem uma conta? <a href="/registro">Registre-se</a></p>
</app-login-register-layout>

// web-quiz/src/pages/login/Login.tsx
import PrimaryButton from "../../components/Buttons/PrimaryButton/PrimaryButton";
import PrimaryInput from "../../components/Inputs/PrimaryInput/PrimaryInput";
import LoginRegisterLogoSide from "../../components/LoginRegisterLogoSide/LoginRegisterLogoSide";
import LoginRequestDTO from "../../models/LoginRequestDTO";
import { loginUser } from "../../services/authService";
import { useNavigate } from "react-router-dom";

import "./Login.scss";

export default function Login() {
  const navigate = useNavigate();

  const handleLogin = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const email = e.currentTarget.email.value;
    const password = e.currentTarget.password.value;

    const login = new LoginRequestDTO(email, password);

    try {
      // chamando o metodo do serviço de autenticação
      const response = await loginUser(login);

      //salvando o token e o id do usuário no localStorage
      localStorage.setItem("authToken", response.token);
      localStorage.setItem("idUser", String(response.usuario.id));

      navigate("/");
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <div className="login-page">
      <LoginRegisterLogoSide />

      <div className="login-area">
        <h1>Entre em sua conta!</h1>
        <form onSubmit={handleLogin}>
          <PrimaryInput
            type="email"
            placeholder="Email"
            labelTitle="E-mail:"
            name="email"
          />
          <PrimaryInput
            type="password"
            placeholder="Senha"
            labelTitle="Senha:"
            name="password"
          />
          <PrimaryButton buttonLabel="Entrar" buttonType="submit" />
        </form>
        <p>
          Não tem uma conta? <a href="/registro">Registre-se</a>
        </p>
      </div>
    </div>
  );
}
