// web-quiz/src/components/Inputs/PrimaryInput/PrimaryInput.tsx
import { ChangeEventHandler, useState } from "react";
import "./PrimaryInput.scss";
import VisibilityOffIcon from "@mui/icons-material/VisibilityOff";
import VisibilityIcon from "@mui/icons-material/Visibility";

interface PrimaryInputProps {
  labelTitle: string;
  type: string;
  placeholder: string;
  onChange?: ChangeEventHandler<HTMLInputElement>;
  name: string;
}

export default function PrimaryInput(props: PrimaryInputProps) {
  const [isPasswordVisible, setIsPasswordVisible] = useState(false);

  const togglePasswordVisibility = () => {
    setIsPasswordVisible((prevState) => !prevState);
  };

  return (
    <div className="primary-input-container">
      <label htmlFor="input">{props.labelTitle}</label>
      <div className="input-wrapper">
        <input
          id="input"
          type={
            props.type === "password" && isPasswordVisible ? "text" : props.type
          }
          placeholder={props.placeholder}
          name={props.name}
          onChange={props.onChange}
        />
        {props.type === "password" && (
          <span className="eye-icon" onClick={togglePasswordVisibility}>
            {isPasswordVisible ? <VisibilityIcon /> : <VisibilityOffIcon />}
          </span>
        )}
      </div>
    </div>
  );
}

// web-quiz/src/app/components/inputs/primary-input/primary-input.component.ts
import { Component, forwardRef, Input } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'app-primary-input',
  imports: [MatIconModule],
  templateUrl: './primary-input.component.html',
  styleUrl: './primary-input.component.scss',
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => PrimaryInputComponent),
      multi: true,
    },
  ],
})
export class PrimaryInputComponent implements ControlValueAccessor {
  @Input() labelTitle!: string;
  @Input() type: string = 'text';
  @Input() placeholder!: string;
  @Input() name: string = '';
  @Input() value?: string;

  isPasswordVisible: boolean = false;
  innerValue: string = '';

  togglePasswordVisibility(): void {
    this.isPasswordVisible = !this.isPasswordVisible;
  }

  get inputType(): string {
    return this.type === 'password' && this.isPasswordVisible
      ? 'text'
      : this.type;
  }

  // Funções do ControlValueAccessor
  onChange: any = () => {};
  onTouched: any = () => {};

  writeValue(value: string): void {
    this.innerValue = value;
  }

  registerOnChange(fn: any): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: any): void {
    this.onTouched = fn;
  }

  setDisabledState?(isDisabled: boolean): void {
    // Lógica para desabilitar o input, se quiser
  }

  onInputChange(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.innerValue = target.value;
    this.onChange(this.innerValue);
    this.onTouched();
  }
}

<div class="primary-input-container">
  <label [for]="name">{{ labelTitle }}</label>
  <div class="input-wrapper">
    <input
      [id]="name"
      [type]="inputType"
      [placeholder]="placeholder"
      [name]="name"
      [value]="innerValue"
      (input)="onInputChange($event)"
    />
    @if (type == 'password') {
    <span class="eye-icon" (click)="togglePasswordVisibility()">
      <mat-icon>{{
        isPasswordVisible ? "visibility" : "visibility_off"
      }}</mat-icon>
    </span>
    }
  </div>
</div>
